preload = /home/tempest/.config/wallpapers/wallz/Catppuccin Mocha/24. Catppuccin Mocha.jpg

wallpaper = HDMI-A-2,/home/tempest/.config/wallpapers/wallz/Catppuccin Mocha/24. Catppuccin Mocha.jpg

splash = false
ipc = off
